apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.17.1
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://$(POSTGRES_EXPORTER_USER):$(POSTGRES_EXPORTER_PASSWORD)@pgvector:5432/$(POSTGRES_EXPORTER_DB)?sslmode=disable"
            - name: POSTGRES_EXPORTER_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-exporter-config
                  key: POSTGRES_EXPORTER_USER
            - name: POSTGRES_EXPORTER_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-exporter-config
                  key: POSTGRES_EXPORTER_DB
            - name: POSTGRES_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: POSTGRES_EXPORTER_PASSWORD
          ports:
            - containerPort: 9187
