apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
data:
  APP_NAME: "RAG pipeline"
  APP_VERSION: "0.1"

  FILE_ALLOWED_TYPES: "application/pdf"
  FILE_MAX_SIZE: "10"
  FILE_DEFAULT_CHUNK_SIZE: "512000" # 512KB

  MONGODB_URL: "mongodb://a:a@localhost:27007/admin?directConnection=true"
  MONGODB_DATABASE: "LLM_QA"

  POSTGRES_USERNAME: "postgres"
  POSTGRES_HOST: "pgvector"
  POSTGRES_PORT: "5432"
  POSTGRES_MAIN_DATABASE: "RAG_QA"

  GENERATION_BACKEND: "OPENAI"
  EMBEDDING_BACKEND: "OPENAI"

  GENERATION_MODEL_ID: "gpt-3.5-turbo-0125"
  EMBEDDING_MODEL_ID: "text-embedding-3-small"
  EMBEDDING_MODEL_SIZE: "1536"

  INPUT_DAFAULT_MAX_CHARACTERS: "1024"
  GENERATION_DAFAULT_MAX_TOKENS: "200"
  GENERATION_DAFAULT_TEMPERATURE: "0.1"

  VECTOR_DB_BACKEND: "PGVECTOR"
  VECTOR_DB_PATH: "qdrant_db"
  VECTOR_DB_DISTANCE_METHOD: "cosine"
  VECTOR_DB_PGVEC_INDEX_THRESHOLD: "100"

  PRIMARY_LANG: "en"
  DEFAULT_LANG: "en"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_USERS_ALLOW_SIGN_UP: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_EXPORTER_USER: "postgres"
  POSTGRES_EXPORTER_DB: "RAG_QA"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
data:
  POSTGRES_EXPORTER_USER: "postgres"
  POSTGRES_EXPORTER_DB: "RAG_QA"
